//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CipherDecrypter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CipherDecrypter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TH	0.0314062703358
        ///HE	0.0298705907066
        ///IN	0.0191955997755
        ///ER	0.0189740694838
        ///AN	0.0182212620818
        ///RE	0.0144342808632
        ///ND	0.014001110025
        ///ED	0.0129884001201
        ///HA	0.0118930119456
        ///ES	0.0118653206592
        ///AT	0.011534211991
        ///TO	0.0115128501415
        ///EN	0.0114994000881
        ///ON	0.0111793679345
        ///HI	0.0105784670183
        ///NT	0.0102113596778
        ///NG	0.0100899136071
        ///EA	0.0100776503231
        ///ST	0.0098126051527
        ///OU	0.0094225536034
        ///AS	0.0091495966369
        ///IS	0.0089229236777
        ///IT	0.0086380990169
        ///OR	0.0081772368922
        ///TE	0.0078710503819
        ///SE	0.007585830 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bigrams {
            get {
                return ResourceManager.GetString("bigrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logotext {
            get {
                object obj = ResourceManager.GetObject("logotext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap padlock {
            get {
                object obj = ResourceManager.GetObject("padlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THAT	-1.98299751071428
        ///THER	-1.99477592385331
        ///WITH	-2.21999809668992
        ///DTHE	-2.25772665560541
        ///NTHE	-2.35457917450529
        ///OTHE	-2.3736643977235
        ///OFTH	-2.4521323721077
        ///TTHE	-2.47595697094825
        ///FTHE	-2.5040149237434
        ///TION	-2.52829095644856
        ///THES	-2.57802909166649
        ///EAND	-2.58527788782217
        ///HERE	-2.60015878429631
        ///INGT	-2.68341392609476
        ///ANDT	-2.68414376434635
        ///SAND	-2.70653918785488
        ///ETHE	-2.74562053789735
        ///THEM	-2.76179621018138
        ///THEC	-2.79061357247057
        ///NDTH	-2.81084942840994
        ///TOTH	-2.87501969323696
        ///EDTH	-2.894 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quadgrams {
            get {
                return ResourceManager.GetString("quadgrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aahing aaliis aarrgh abacas abacus abakas abamps abased abaser abases
        ///abasia abated abater abates abatis abator abayas abbacy abbess abbeys
        ///abbots abduce abduct abeles abelia abhors abided abider abides abject
        ///abjure ablate ablaut ablaze ablest ablins abloom ablush abmhos aboard
        ///aboded abodes abohms abolla abomas aboral aborts abound aboves abrade
        ///abroad abrupt abseil absent absorb absurd abulia abulic abused abuser
        ///abuses abvolt abwatt abying abysms acacia acajou acarid acarus accede
        ///accent accept a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wordlist6letter {
            get {
                return ResourceManager.GetString("wordlist6letter", resourceCulture);
            }
        }
    }
}
